apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo-2
  namespace: bykov1021
spec:
  containers:
    - name: cpu-demo-2-ctr
      image: vish/stress
      resources:
        limits:
          cpu: "100"
        requests:
          cpu: "100"
      args: 
        - -cpus
        - "2"
